kind: Service
apiVersion: v1
metadata:
  name: cassandra-service
  namespace: {{ .Values.image.namespace }}
spec:
  ports:
    - port: 9160
      targetPort: 9160
      name: thrift
    - port: 9042
      targetPort: 9042
      name: cql
    - port: 7199
      targetPort: 7199
      name: jmx
  selector:
    app: cassandra
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra
  namespace: {{ .Values.image.namespace }}
spec:
  replicas: {{ .Values.cassandra.replicas }}
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: {{ .Values.image.registry_path }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 7000
            - containerPort: 7199
            - containerPort: 9042
            - containerPort: 9160
            - containerPort: 61621
          imagePullPolicy: Always
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: cassandra-disk
  namespace: {{ .Values.image.namespace }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: europe-west1-d