{{ if .Values.storage }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Name}}-aws-credentials"
type: Opaque
data:
  awsAccessKeyId: {{ .Values.storage.awsAccessKeyId }}
  awsSecretAccessKey: {{ .Values.storage.awsSecretAccessKey }}
{{- end }}