apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.image.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: {{ .Values.image.registry_path }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5601
          volumeMounts:
          - name: config-volume
            mountPath: /opt/kibana/config
      volumes:
      - name: config-volume
        configMap:
          name: kibana-config