apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tuple (print (include "name" .) "-broker") . | include "fqan" }}
  labels:
    app: {{ tuple (print (include "name" .) "-broker") . | include "fqan" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  jvm.config: |
{{ include (print $.Template.BasePath "/etc/broker/_jvm.config.tpl") . | indent 4  }}
  runtime.properties: |
{{ include (print $.Template.BasePath "/etc/broker/_runtime.properties.tpl") . | indent 4  }}
