apiVersion: v1
kind: Service
metadata:
  name: {{ tuple (print (include "name" .) "-broker") . | include "fqan" }}
  labels:
    app: {{ tuple (print (include "name" .) "-broker") . | include "fqan" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: broker
    port: {{ default 8082 .Values.broker.port }}
    targetPort: broker
    protocol: TCP
  selector:
    app: {{ tuple (print (include "name" .) "-broker") . | include "fqan" }}
