apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tuple (print (include "name" .) "-common") . | include "fqan" }}
  labels:
    app: {{ tuple (print (include "name" .) "-common") . | include "fqan" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  common.runtime.properties: |
{{ include (print $.Template.BasePath "/etc/_common/_common.runtime.properties.tpl") . | indent 4  }}
  log4j2.xml: |
{{ include (print $.Template.BasePath "/etc/_common/_log4j2.xml.tpl") . | indent 4  }}
