apiVersion: v1
kind: Service
metadata:
  name: {{ tuple (print (include "name" .) "-coordinator") . | include "fqan" }}
  labels:
    app: {{ tuple (print (include "name" .) "-coordinator") . | include "fqan" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: coordinator
    port: {{ default 8081 .Values.coordinator.port }}
    targetPort: coordinator
    protocol: TCP
  selector:
    app: {{ tuple (print (include "name" .) "-coordinator") . | include "fqan" }}
