apiVersion: v1
kind: Service
metadata:
  name: {{ tuple (print (include "name" .) "-historical") . | include "fqan" }}
  labels:
    app: {{ tuple (print (include "name" .) "-historical") . | include "fqan" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  ports:
  - name: historical
    port: {{ default 8083 .Values.historical.port }}
    targetPort: historical
    protocol: TCP
  selector:
    app: {{ tuple (print (include "name" .) "-historical") . | include "fqan" }}
