apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ tuple (print (include "name" .) "-middlemanager") . | include "fqan" }}
  labels:
    app: {{ tuple (print (include "name" .) "-middlemanager") . | include "fqan" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ tuple (print (include "name" .) "-middlemanager") . | include "fqan" }}
  replicas: {{ default 2 .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ tuple (print (include "name" .) "-middlemanager") . | include "fqan" }}
      annotations:
        checksum/config-common: {{ include (print $.Template.BasePath "/common-configmap.yaml") . | sha256sum  }}
        checksum/config-middlemanager: {{ include (print $.Template.BasePath "/middlemanager-configmap.yaml") . | sha256sum  }}
    spec:
      containers:
      - name: druid
        image: "{{ .Values.image.registry_path }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pull_policy }}
        args:
        - druid
        - start
        - middleManager
        ports:
        - name: middlemanager
          containerPort: 8090
          protocol: TCP
        - name: peon1
          containerPort: 8100
          protocol: TCP
        - name: peon2
          containerPort: 8101
          protocol: TCP
        - name: peon3
          containerPort: 8102
          protocol: TCP
        resources:
{{ toYaml .Values.middlemanager.resources | indent 10 }}
        volumeMounts:
        - mountPath: /opt/druid/conf/druid/_common
          name: common-config-volume
        - mountPath: /opt/druid/conf/druid/middleManager
          name: middlemanager-config-volume
      initContainers:
      - name: wait-for-zookeeper
        image: busybox
        command: ['sh', '-c', 'until nslookup  {{ default "zookeeper" .Values.init.zookeeper  }}; do echo waiting for zookeeper; sleep 2; done;']
      volumes:
      - name: common-config-volume
        configMap:
          name: {{ tuple (print (include "name" .) "-common") . | include "fqan" }}
      - name: middlemanager-config-volume
        configMap:
          name: {{ tuple (print (include "name" .) "-middlemanager") . | include "fqan" }}

