apiVersion: v1
kind: Service
metadata:
  name: {{ tuple (print (include "name" .) "-middlemanager") . | include "fqan" }}
  labels:
    app: {{ tuple (print (include "name" .) "-middlemanager") . | include "fqan" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  ports:
  - name: middlemanager
    port: {{ default 8091 .Values.middlemanager.port }}
    targetPort: middlemanager
    protocol: TCP
  - name: peon1
    port: {{ default 8100 .Values.peon1.port }}
    targetPort: peon1
    protocol: TCP
  - name: peon2
    port: {{ default 8101 .Values.peon2.port }}
    targetPort: peon2
    protocol: TCP
  - name: peon3
    port: {{ default 8102 .Values.peon3.port }}
    targetPort: peon3
    protocol: TCP
  selector:
    app: {{ tuple (print (include "name" .) "-middlemanager") . | include "fqan" }}
