apiVersion: v1
kind: Service
metadata:
  name: {{ tuple (print (include "name" .) "-overlord") . | include "fqan" }}
  labels:
    app: {{ tuple (print (include "name" .) "-overlord") . | include "fqan" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: overlord
    port: {{ default 8090 .Values.overlord.port }}
    targetPort: overlord
    protocol: TCP
  selector:
    app: {{ tuple (print (include "name" .) "-overlord") . | include "fqan" }}
