apiVersion: v1
kind: Service
metadata:
  name: mattermost-loader
  namespace: {{ .Values.image.namespace }}
  labels:
    component: mattermost-loader
spec:
  ports:
  - name: http
    port: 8250
    targetPort: 8080
  selector:
    component: mattermost-loader
  type: LoadBalancer
  loadBalancerIP: {{ .Values.conn.public_ip }}
