apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ .Values.image.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: redis
    port: {{ default 6379 .Values.port }}
    targetPort: redis
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}