apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs
  namespace: {{ .Values.image.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: nfs
    spec:
      containers:
      - name: nfs
        image: {{ .Values.image.registry_path }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs