apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: {{ .Values.image.namespace }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ .Values.volume.storageClass }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.volume.storage }}