apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.image.namespace }}
  labels:
    component: elasticsearch
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: discovery
      port: 9300
      targetPort: 9300
  selector:
    component: elasticsearch
  type: LoadBalancer
