apiVersion: v1
kind: Service
metadata:
  name: {{ template "hdfs-datanode-fqan" . }}
  labels:
    app: {{ template "hdfs-datanode-fqan" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  ports:
  - name: http
    port: {{ default 50075 .Values.hdfs.datanode.ports.http }}
    targetPort: http
    protocol: TCP
  - name: xceiver
    port: {{ default 50010 .Values.hdfs.datanode.ports.xceiver }}
    targetPort: xceiver
    protocol: TCP
  - name: ipc
    port: {{ default 50020 .Values.hdfs.datanode.ports.ipc }}
    targetPort: ipc
    protocol: TCP
  selector:
    app: {{ template "hdfs-datanode-fqan" . }}
