apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: {{ .Values.image.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  logstash.conf: |
{{ include (print $.Template.BasePath "/conf/_logstash.conf.tpl") . | indent 4 }}
  logstash.yml: |
{{ include (print $.Template.BasePath "/conf/_logstash.yml.tpl") . | indent 4 }}