apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: {{ .Values.image.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "imagePullPolicy": "IfNotPresent",
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
        - name: logstash
          image: {{ .Values.image.registry_path }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          command:
          - sh
          - -c
          - "logstash -f /opt/logstash/config/logstash.conf"
          volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config/
          - name: config-volume
            mountPath: /usr/share/logstash/pipeline/
      volumes:
      - name: config-volume
        configMap:
          name: logstash-config