apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.image.namespace }}
  labels:
    app: mysql
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: mysql
    port: {{ default 3306 .Values.port }}
    targetPort: {{ default 3306 .Values.port }}
  selector:
    app: mysql