# Default values for hivemq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  registry_path: "dockerImageRegestry"
  name: "docker-zeppelin"
  #name: "zeppelin-data"
  tag: 0.7.1
  pullPolicy: Always
  namespace: kubeyard
service:
  httpPort: 8080
  sparkUiPort: 4040
  sshPort: 22
# storage:
#   awsAccessKeyId: ""
#   awsSecretAccessKey: ""
#   zeppelinNotebookS3Bucket: ""
#   zeppelinNotebookS3User: ""
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
