apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: newsflash-loader-deployment
  namespace: {{ .Values.image.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: newsflash-loader
    spec:
      containers:
        - name: newsflash-loader
          image: {{ .Values.image.registry_path }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          args: ["--inputmode", "gmail", "--outputmode", "kafka", "--scheduled", "--kafka", "kafka.kubeyard:9092", "--topic", "test", "--credentials", "/loader/credentials/"]
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "0"
